### ISSUE TITLE
Missing a 48x48 icon

### ISSUE THREAD

**Issue by LazyKent** [mones/clawsker#15]
According [freedesktop.org specifications](https://specifications.freedesktop.org/icon-theme-spec/latest/ar01s07.html) an application should install a 48x48 icon.
Please add.

**Comment by mones** [comment]
It says "minimally you should install", which basically means "if you only install one icon, it should be the 48x48 icon". But currently higher resolution icons are installed, so lacking the 48x48 one should not be a problem.

Have you found real a desktop environment where the application icon is not shown?

**Comment by LazyKent** [comment]
> It says "minimally you should install", which basically means "if you only install one icon, it should be the 48x48 icon".

It means, the 48x48 icon is shown in every desktop environment.

> Have you found real a desktop environment where the application icon is not shown?

Yes, I have. Running Xfce 4.12 in openSUSE Tumbleweed (Whisker Menu).
Please, look at a screenshot:
[clawsker-missing-icon-xfce-opensuse.png](http://storage1.static.itmages.ru/i/16/1011/h_1476201754_3994759_6af52ef7cc.png)

**Comment by LazyKent** [comment]
Just tested with the 48x48 icon.
```
# convert -resize 48x48 -strip /usr/share/icons/hicolor/64x64/apps/clawsker.png -strip /usr/share/icons/hicolor/48x48/apps/clawsker.png
# gtk-update-icon-cache /usr/share/icons/hicolor
```
And here it is:
[clawsker-using-icon-48x48-xfce-opensuse.png](http://storage6.static.itmages.ru/i/16/1011/h_1476216775_2898082_48aeeb367e.png)

**Comment by mones** [comment]
Both screenshots show the same icon :-) Anyway, it's clear the 48x48 is needed for some desktops (but others like KDE seem happy with current iconset and don't miss the lower resolution one).

Thanks for the feedback!
